######################################################################
# Automatically generated by qmake (2.01a) su syyskuuta 27 12:32:35 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
